/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Distributed_System_Java_Src;

public class App {
    public String getGreeting() {
        return "Hellorld Wo";
    }
    

}
